"""Add created column

Revision ID: 0380275520f2
Revises: dcdd6106373a
Create Date: 2017-04-07 15:21:16.469604

"""
import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0380275520f2'
down_revision = 'dcdd6106373a'
branch_labels = None
depends_on = None


statement_helper = sa.Table(
    'statements',
    sa.MetaData(),
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('created', sa.DateTime),
)


def upgrade():
    connection = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    connection.execute(
        statement_helper.update().where(
            statement_helper.c.created == None
        ).values(
            created=datetime.datetime.utcnow()
        )
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'created')
    # ### end Alembic commands ###
